name: flutter_playground
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  scoped_model: ^0.2.0
  http: ^0.11.3+16
  built_value: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^0.7.9
  built_value_generator: ^5.4.3


flutter:
  uses-material-design: true
  assets:
    - assets/challenge01/hero.jpg
    - assets/challenge01/avatar.jpg
    - assets/challenge02/venice01.jpg
    - assets/challenge02/venice02.jpg
    - assets/challenge02/venice03.jpg
    - assets/recipes/pasta-alla-siciliana.jpg
